### ISSUE TITLE
error APT2144: invalid file path '.\src\qs\MapboxMauiQs\obj\Debug\net8.0-android\lp\188.stamp'.

### ISSUE THREAD

**Issue by tuyen-vuduc** [tuyen-vuduc/mapbox-maui#10]
![image](https://github.com/tuyen-vuduc/mapbox-maui/assets/3112460/4abdaf2b-5a5f-4a0e-aaef-574a520b9617)

Similar issues:
- https://github.com/xamarin/xamarin-android/issues/7660
- https://github.com/dotnet/maui/issues/16680

**Comment by tuyen-vuduc** [comment]
[The sample app for .NET Android](https://github.com/tuyen-vuduc/dotnet-mapbox-quickstart/tree/main/src/quickstart/DotnetAndroid.MapboxQs) is running well without issues.

**Comment by sergsel** [comment]
Any progress so far? I have the same issue during build using windows.

**Comment by tuyen-vuduc** [comment]
Workaround applied to[ branch v11.0.0](https://github.com/tuyen-vuduc/mapbox-maui/tree/feat/v11.0.0). Please check it out.

**Comment by tuyen-vuduc** [comment]
Considered closed for now.

**Comment by sklyarovaleksey** [comment]
Hello this works in vension 11.3 but doesn't work on version 11.5 (net8.0-android34.0)

Project Settings
`<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
    <PackageReference Include="Com.Mapbox.Maps.Android" Version="11.5.0" />
    <PackageReference Include="Xamarin.AndroidX.Fragment.Ktx" Version="1.7.0.2" />
    <PackageReference Include="Xamarin.Kotlin.StdLib.Jdk8" Version="2.0.0" />
    <PackageReference Include="Square.OkHttp3" Version="4.12.0.4" />
    <PackageReference Include="Xamarin.Kotlin.StdLib" Version="2.0.0" />
    <PackageReference Include="Xamarin.AndroidX.Annotation" Version="1.8.0" />
    <PackageReference Include="Xamarin.Android.Google.BillingClient" Version="6.2.1" />
    <PackageReference Include="Square.OkIO" Version="3.9.0" />
  </ItemGroup>` 

Error

**Comment by sklyarovaleksey** [comment]
In addition to the previous post.
This issue occurred when you try to use dependences with different project. For instance when you use two project with dependences like in the example (libs and qs projects). 
And works good when you combine all in one project.
![image](https://github.com/user-attachments/assets/1076d56b-5f36-494f-8dec-b07a30771898)

**Comment by tuyen-vuduc** [comment]
Workaround: Add these lines to your lib CSPROJ file.
```
	<Target Name="_CleanAarOutputPath" AfterTargets="_CreateAar" BeforeTargets="_IncludeAarInNuGetPackage">
		<Delete Files="$(_AarOutputPath)" />
	</Target>
```

**Comment by tuyen-vuduc** [comment]
@sklyarovaleksey The workaround is not that correct to use the lib as a ProjectReference, it's for packing the nuget package only :D . It's used to mentioned in [this issue](https://github.com/dotnet/android/issues/8699). 

The actual workaround for this situation is to link files directly to the main .NET MAUI app project.

You can check out file `MapboxMauiQs.csproj` to see how I apply it.

1/ For Android

```
<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'android'">
   <Compile Include="..\..\libs\Mapbox.Maui\Platforms\Android\**\**\*.cs">
	<Link>Platforms\Android\Shared\%(RecursiveDir)%(Filename)%(Extension)</Link>
   </Compile>
</ItemGroup>
```

2/ For iOS

```
<ItemGroup Condition="$([MSBuild]::GetTargetPlatformIdentifier('$(TargetFramework)')) == 'ios'">
	<Compile Include="..\..\libs\Mapbox.Maui\Platforms\iOS\**\**\*.cs">
		<Link>Platforms\iOS\Shared\%(RecursiveDir)%(Filename)%(Extension)</Link>
	</Compile>
</ItemGroup>
```

3/ For both

```
<Compile Include="..\..\libs\Mapbox.Maui\Models\**\**\*.cs">
      <Link>Shared\%(RecursiveDir)%(Filename)%(Extension)</Link>
</Compile>
```

If you have multiple .NET MAUI app projects, you may consider to use local Nuget package for the others. Only single project will be use this workaround.

**Comment by tuyen-vuduc** [comment]
https://github.com/dotnet/android/issues/8699

**Comment by tuyen-vuduc** [comment]
https://github.com/dotnet/android/issues/8504

**Comment by tuyen-vuduc** [comment]
@leoslima13  Add these lines to your Android lib project.

```
	<Target Name="_CleanAarOutputPath" AfterTargets="_CreateAar" BeforeTargets="_IncludeAarInNuGetPackage">
		<Delete Files="$(_AarOutputPath)" />
	</Target>
```


![image](https://github.com/user-attachments/assets/cd860629-4b3f-4667-b3e1-487bdea612eb)

**Comment by leoslima13** [comment]
@tuyen-vuduc Actually I don't have any lib project, I have two .NET MAUI single projects.
I tried what you sent on my two projects, but still not working.
I'm sharing a link to my personal drive with the zip file of my solution (removing all my mapbox tokens) if you want try on your end. (https://drive.google.com/file/d/1u9XykbN_dlQOjKlpavF17ONE0RCU6aKq/view?usp=drive_link)
Basically this project is the same as your sample, adding an extra project.

**Comment by tuyen-vuduc** [comment]
Plz slowly read and follow my instruction.

**Comment by leoslima13** [comment]
I already followed the steps you said earlier, I sent the answer with the sample project because it didn't work

**Comment by leoslima13** [comment]
Hey @tuyen-vuduc any thoughts on that? Even following your steps, I still getting the same error.

**Comment by tuyen-vuduc** [comment]
Hi @leoslima13 ,

Sorry, [the actual steps](https://github.com/tuyen-vuduc/mapbox-maui/issues/10#issuecomment-2241635973) were listed previous for `sklyarovaleksey`. Please take a look.

IMPORTANT: We cannot add project reference directly.
