### ISSUE TITLE
Missing RasterSource

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#19]
Similar to RasterDemSource, add support for RasterSource (https://docs.mapbox.com/help/glossary/raster/)

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410  Check out [v11.5.1-alpha06](https://www.nuget.org/packages/Mapbox.Maui/11.5.1-alpha06) and example [RasterTileSourceExample](https://github.com/tuyen-vuduc/mapbox-maui/blob/main/src/qs/MapboxMauiQs/Examples/Styles/73.RasterTileSource/RasterTileSourceExample.cs)

**Comment by DincaAndrei2410** [comment]
Works, closing issue
