### ISSUE TITLE
Mapbox.Maui(Version 10.11.1.1)  - not working with MAUI

### ISSUE THREAD

**Issue by riburajan** [tuyen-vuduc/mapbox-maui#2]
After installing Mapbox.Maui(Version 10.11.1.1) NuGet package, we are not able to build the project getting an error like :

Gradlew build failed \\..MapBox.Maui.Map\obj\xgradle\gradlew.bat --> MapBox.Maui.Map \\.nuget\packages\dependencies.gradle\7.6.0.1\buildTransitive\Dependencies.Gradle.targets

any solution for resolving this issue ?

https://github.com/dotnet/maui/discussions/578#discussioncomment-7300820 -- I think this guy also getting same issue.

**Comment by tuyen-vuduc** [comment]
Closed as no more info. Plz raise another issue in case.
