### ISSUE TITLE
Detect camera viewport change

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#21]
Expose an event that triggers when camera is moved to another location. The event could return a Bounds object that represents the coordinates for the box defined by camera new location

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 Can you describe the use case with more details? If there is a ref to a native example, it'll be very great.

**Comment by DincaAndrei2410** [comment]
For Android I've found [this](https://docs.mapbox.com/android/maps/guides/camera-and-animation/camera/#listen-for-camera-changes).

What we need to know is when user scrolls the map to another location for loading specific map feature linked to the new location

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410  Plz check out `CameraChanged` event and command to see if it fits your need.

**Comment by DincaAndrei2410** [comment]
Looks good, I've checked in on feat/sample-advanced-viewport-gestures.
