### ISSUE TITLE
Location Pin

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#22]
Expose shared property that can handle showing/hiding location pin. Maybe also expose property for controlling if pulsing is enabled for pin

**Comment by DincaAndrei2410** [comment]
On iOS, I can't find something similar to [this](https://docs.mapbox.com/ios/maps/guides/user-location/#location-puck)

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 Please check out the sample [BasicLocationPulsingCircleExample](https://github.com/tuyen-vuduc/mapbox-maui/blob/feat/mapbox-annotation-update/src/qs/MapboxMauiQs/Examples/Lab/70.BasicLocationPulsingCircle/BasicLocationPulsingCircleExample.cs)

**Comment by DincaAndrei2410** [comment]
Checked and it works. Thanks!
