### ISSUE TITLE
Disable/Enable map interaction

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#23]
There are times when you'd need to restrict map gestures for end user. Expose such capability in shared component

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 You should be able to check out the new API to get this happen. I am creating the sample page for this

**Comment by tuyen-vuduc** [comment]
Check it out with this version: https://www.nuget.org/packages/Mapbox.Maui/11.4.0-alpha02

**Comment by DincaAndrei2410** [comment]
Works with latest version
