### ISSUE TITLE
AnnotationManagers issues

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#24]
CircleAnnotationManager, PointAnnotationManager and PolygonAnnotationManager have issues when removing annotations:
- RemoveAllAnnotations doesn't seem to do anything 
- RemoveAnnotations(param annotationIds) is hard to use because I've seen the native annotation managers assign a different id rather than the one I fill for shared Annotation object Id

**Comment by tuyen-vuduc** [comment]
Please check out the new build https://mail.zoho.com/zm/#mail/folder/8980031000000028007/p/1720745658034116600

**Comment by DincaAndrei2410** [comment]
Link doesn't work for me, but I've checked latest version for branch fix/24-annotationmanagers-issues, AddRemoveAnnotationsExample looks good. On purpose you did not want to remove annotations from circle manager?

**Comment by tuyen-vuduc** [comment]
Haha. Wrong copy :D Here is the link to the new package version. https://www.nuget.org/packages/Mapbox.Maui/11.5.0-alpha01

**Comment by tuyen-vuduc** [comment]
> On purpose you did not want to remove annotations from circle manager?

That's a "bug" :D . A lot of code changes in iOS native ObjC to get iOS working then I forgot about handling circle ones.
