### ISSUE TITLE
Visibility property for MapboxLayer doesn't seem to work

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#25]
Trying to hide/show MapboxLayer doesn't work. I've checked HandleSourcesChanged method from MapboxViewHandler and there doesn't seem to be a logic that listens for changes to that property.

As a workaround after updating visibility, I manually call "OnPropertyChanged(nameof(Layers))"

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 Yeah, that's right. I think we will use the controller base approach where will have a controller to call action on a particular layer/source. Listening to every individual property will cause a lot of headaches
.

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 Check out [v11.5.1-alpha07](https://www.nuget.org/packages/Mapbox.Maui/11.5.1-alpha07) for `SetLayerPropertyFor`

**Comment by DincaAndrei2410** [comment]
Looks good, closing issue
