### ISSUE TITLE
iOS map events not fired

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#29]
There are times when map is loaded but neither MapLoaded, neither StyleLoaded are triggered. 
Tried with MultipleGeometriesExample

**Comment by tuyen-vuduc** [comment]
Yeah. It is a bug. I recognized it when checking the issue of removing annotations. Only on iOS, right?

**Comment by DincaAndrei2410** [comment]
Right, only iOS. As a workaround I've hooked logic to MapReady. 

There is a problem, however, when trying to add GeoJsonSource inside map ready. Maybe because not everything is properly loaded at that point. Adding a small Task.Delay seems to solve the problem, but this solution might not be proper for all cases due to concurrency

**Comment by tuyen-vuduc** [comment]
Yep. Map ready is a fake event on iOS. It is only available for Android natively. 😀

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410  This will be fixed in the new build. Plz check it out.
