### ISSUE TITLE
Target net6.0

### ISSUE THREAD

**Issue by samuelsandri** [tuyen-vuduc/mapbox-maui#3]
Target net6.0 to allow building projects for testing.
Would also be good to update to .NET 8

**Comment by tuyen-vuduc** [comment]
The chosen of .NET6 is for .NET6+ uses. It means .NET6, .NET7 & .NET8. But, we cannot target both .NET 6 & .NET8 together.

**Comment by samuelsandri** [comment]
Still nice to target net6 for test projects etc. Have opened PR with changes needed https://github.com/tuyen-vuduc/mapbox-maui/pull/4

**Comment by tuyen-vuduc** [comment]
@samuelsandri That's a good point. There was an issue last time, hence I removed it. I will check it again on my Mac
