### ISSUE TITLE
View Center Update / Light Changes (Manual or presets) / ScaleBarVisibility

### ISSUE THREAD

**Issue by NicolaSchueeppAventit** [tuyen-vuduc/mapbox-maui#31]
First, I want to express my gratitude for your voluntary work on this project. I am excited to use it in our project. The performance is excellent, and you have done exceptionally good work. However, I have encountered a few issues that I need assistance with:

1. Center Update Issue: It seems that the center of the view is not being updated. Is there a way to react to screen or camera changes
2. Light Changes: Manual light changes do not seem to work. Would it be possible to make the light presets accessible? Alternatively, could you provide an easier way to access or modify the platform-specific code?

[From Android SDK](https://docs.mapbox.com/android/maps/guides/styles/set-a-style/#mapbox-standard-1)
```
mapboxMap.loadStyle(Style.STANDARD) { style ->
  style.setStyleImportConfigProperty(styleImportId, "lightPreset", Value.valueOf("dusk"))
}
```

3. ScaleBar Visibility: The ScaleBar visibility is currently not working, or perhaps I'm doing something wrong.

Everything else is working very well.

Thank you again for your hard work and support.

**Comment by tuyen-vuduc** [comment]
@NicolaSchueeppAventit 

1/ Center of the map

You can listen for `CameraChanged` event/command

2/ Light changes
- it's not yet integrated yet for the current version
- you can change the way you want following [.NET MAUI handler approach](https://learn.microsoft.com/en-us/dotnet/maui/user-interface/handlers/?view=net-maui-8.0).
