### ISSUE TITLE
Update method for annotation managers

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#33]
![image](https://github.com/user-attachments/assets/525bebef-bb84-4f5b-8c1b-4710223f8a2b)

In addition to Add, Remove and RemoveAll, would be good to have also an Update method. Use case would be to move annotation to a different coordinate without Removing and then adding a new one

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 I added `updateAnimations` method.

- On Android, it's a call to the native method, 
- On iOS it's the removing then adding again.

Let me know if you find out any issues.

https://www.nuget.org/packages/Mapbox.Maui/11.5.1-alpha02

**Comment by DincaAndrei2410** [comment]
I see the Update method, but I also need Geometry property setter to be exposed publicly, otherwise I can't move the same annotation to another position.
![image](https://github.com/user-attachments/assets/df6e650b-3627-4cdb-9c90-8c1735efa626)

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 It's readonly aligned with the native impl. :D .

I recommend creating a new instance with the same ID for now.

**Comment by DincaAndrei2410** [comment]
Ok, let me check how it behaves with new instance, but same id. Indeed, I did not keep id, so maybe that's why flickering problem occurred

**Comment by tuyen-vuduc** [comment]
Report another issue if that tip doesn't work then.
