### ISSUE TITLE
AnnotationManager, Add changes given Id

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#36]
On nuget version 11.5.1-alpha02, every time I try to add an annotation with a given id, after calling [manager].AddAnnotations(), that id is changed automatically

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 On Android, the id is generated when we adding a new annotation. That ID will be reassigned back to the shared instance. Check the source you will see that logic.

I believe the ID won't change for the update.

**Comment by DincaAndrei2410** [comment]
Could you provide an example with a PointAnnotation which moves to a different position 2 times every second?

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 You're right. Actually, we should be able to change to `geometry` property. 

I adjusted the logic so we do that and also created an example for reference `MovingCarExample`.

To use in your project, please update the nuget package to `v11.5.1-alpha04`
