### ISSUE TITLE
PolygonAnnotationManager, Update issue

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#37]
Trying to use Update() method on a polygon annotations leads to annotation being removed.

Following error observed in logs:
[maps-android\AnnotationManagerImpl]: Can't update annotation: com.mapbox.maps.plugin.annotation.generated.PolygonAnnotation@f450df5, the annotation isn't an active annotation.

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410  I made [an example](https://github.com/tuyen-vuduc/mapbox-maui/blob/main/src/qs/MapboxMauiQs/Examples/Lab/72.ChangingPolygon/ChangingPolygonExample.cs) for your reference. I can change a polygon annotation's geometry value, fill color, and fill outline color.

Plz check it out.

BTW: The opacity was default to null, then the annotation might not shown, you can upgrade to the newly built version to avoid setting a opacity value.

**Comment by DincaAndrei2410** [comment]
Right, the issue was on my side. Thanks for help!
