### ISSUE TITLE
WMTS example

### ISSUE THREAD

**Issue by DincaAndrei2410** [tuyen-vuduc/mapbox-maui#39]
Could you provide an example of how to set a custom map using WMTS service?

You can use the following endpoint: https://services.arcgisonline.com/arcgis/rest/services/World_Imagery/MapServer/WMTS/tile/1.0.0/World_Imagery/default/default028mm/%7Bz%7D/%7By%7D/%7Bx%7D.jpg

**Comment by tuyen-vuduc** [comment]
@DincaAndrei2410 Please check out [this example](https://github.com/tuyen-vuduc/mapbox-maui/blob/c8bd89ffb2fa486e51556ee40668ba5007d8e7cc/src/qs/MapboxMauiQs/Examples/Styles/73.RasterTileSource/RasterTileSourceExample.cs#L81). 

Let me know if it works for you.

**Comment by DincaAndrei2410** [comment]
Right, looks like what I need. Thank you
