### ISSUE TITLE
ScaleBarVisibility not working

### ISSUE THREAD

**Issue by NicolaSchueeppAventit** [tuyen-vuduc/mapbox-maui#43]
Hi, just saw that the Settings Scalebarvisibility is not working for me. No matter if I set it in OnMapReady or OnMapLoaded.

`Mapbox.ScaleBarVisibility = OrnamentVisibility.Hidden;`

Do I have to implement this via Platform specific handler?
And is it possible to relocate the default compass or disable it too?

Thanks for your hel and keep up the good work :)

**Comment by tuyen-vuduc** [comment]
Visible 

![image](https://github.com/user-attachments/assets/71bcfd96-efac-4367-9013-7c5a8947e86c)

Hidden

![image](https://github.com/user-attachments/assets/edf1fe09-19ca-48fa-a908-596fd704aafa)

**Comment by tuyen-vuduc** [comment]
@NicolaSchueeppAventit Check out the latest build to see if the issue still persists. 

https://www.nuget.org/packages/Mapbox.Maui/11.6.0-alpha02

**Comment by tuyen-vuduc** [comment]
Closing as no further info.
