### ISSUE TITLE
Deploying 10.11.1.1 for iOS on .NET 8 Maui results in download failed

### ISSUE THREAD

**Issue by jmielczarkowski** [tuyen-vuduc/mapbox-maui#5]
Hi, 

I've got question. I was able to deploy app under .NET 8 Maui program using Android (on Visual Studio on PC) and MacOS (on Visual Studio on Mac), but I can't deploy it for iOS.
I follow guide ref: https://tuyenvu.hashnode.dev/how-to-use-mapbox-in-your-dotnet-maui-app but I get error:

![Screenshot 2024-03-21 at 14 31 24](https://github.com/tuyen-vuduc/mapbox-maui/assets/8956841/0f1085d3-2f8f-47ec-a165-6cd9c959f473)

Manually I am able to download that package using my token. I setup download token stuff in:
- .netrc file 
- dev.cs / props
![Screenshot 2024-03-21 at 14 30 51](https://github.com/tuyen-vuduc/mapbox-maui/assets/8956841/e7ba087a-a0c8-47a7-a361-59b2a6f9bd2f)

I validate that download token is fine by entering this url manually and getting file. 
I was thinking that maybe it's due linker option or something, so I setup new empty project and just added package 10.11.1.1. Still couldn't deploy / error is always same. 

Any suggestion what I can check?

**Comment by tuyen-vuduc** [comment]
No. You need to specify YOUR_MAPBOX_DOWNLOADS_TOKEN in  your CSPROJ file.

Please check the guide again then. ;)

Cheers.

**Comment by jmielczarkowski** [comment]
It's added too, but I will double check if token is correctly used. Thanks.

**Comment by tuyen-vuduc** [comment]
@jmielczarkowski  How was it going?

**Comment by jmielczarkowski** [comment]
@tuyen-vuduc so generally package download it's working but then it gives me compilation error while I am trying to deploy it to real device (my iPhone). No matter what linker setup I used it was giving me same result. From what I understood it's up to not supporting .NET 8 Maui by package. 

I've created sample project on .NET MAUI 8 and just put there our package and that's result. If you wish I can share solution, but there's nothing more than empty MAUI project + our package + key for download.

![Screenshot 2024-03-22 at 13 54 53](https://github.com/tuyen-vuduc/mapbox-maui/assets/8956841/f58b4855-96ec-4f7b-a059-671abebbb6e9)

@tuyen-vuduc Can you estimate when this package will support .NET 8?

**Comment by tuyen-vuduc** [comment]
@jmielczarkowski The package works with .NET 8 as default. No further action is required.
